### ISSUE TITLE
Delay not working because wrong attribute

### ISSUE THREAD

**Issue by mxmihai** [chrisgo/bootstrap5-toast#3]
Maybe the delay shoule be more flexible.

instead of:

        let delayOrAutohide = opts.delay ? `data-delay="${opts.delay}"` : `data-autohide="false"`;

maybe:

        let delayOrAutohide = opts.delay ? `data-delay="${opts.delay}"` : `data-bs-autohide="false"`;

**Comment by mxmihai** [comment]
also, instead of:

    delayOrAutohide = `data-autohide="false"`;

it should be:

    delayOrAutohide = `data-bs-autohide="false"`;

**Comment by mxmihai** [comment]
also, instead of:

    if ($.toastDefaults.pauseDelayOnHover) {

it shoudl be:

    if ($.toastDefaults.pauseDelayOnHover && opts.delay) {

**Comment by chrisgo** [comment]
@mxmihai thank you for hunting this down, I was just getting back to this and found these problems and you already got the code ready :) 

In addition to the items here (plus #1 and #2), also fixed 2 more

* the positioning `position-absolute` needed to be `position-fixed` in the toast-container 
* `data-delay` is now `data-bs-delay`
